import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {DisplayAudio} from '../public/display-audio.js';
const source=fs.readFileSync('cloud/clock/index.js','utf8').split('function platformKey(name)')[0];
const sandbox={structuredClone,console,TextEncoder,TextDecoder,URL,URLSearchParams,Response,Request,Headers,crypto:globalThis.crypto};vm.createContext(sandbox);vm.runInContext(source,sandbox);const {Engine}=sandbox;
function command(engine,text,now=1000,id='announcement-1'){return engine.command({id,revision:engine.record.revision,type:'announce',text},now);}
test('announcement trims text, leaves clock and undo unchanged, expires',()=>{const e=new Engine(null,1000);const old=JSON.stringify(e.record.state);const p=command(e,'  Take  your seats. ');assert.equal(p.announcement.text,'Take your seats.');assert.equal(JSON.stringify(e.record.state),old);assert.equal(e.record.history.length,0);assert.equal(e.snapshot(11000).announcement,null);});
test('announcement rejects empty and oversized messages and disabled sound',()=>{for(const text of ['', ' '.repeat(5),'a'.repeat(241),null])assert.throws(()=>command(new Engine(null,1000),text));const e=new Engine(null,1000);e.record.state.appearance.soundEnabled=false;assert.throws(()=>command(e,'Hi'));});
test('announcement retries are idempotent and new commands rate limited',()=>{const e=new Engine(null,1000);command(e,'Hi');e.command({id:'announcement-1',revision:0,type:'announce',text:'Hi'},1001);assert.equal(e.record.revision,1);assert.throws(()=>command(e,'Again',1002,'announcement-2'));assert.equal(command(e,'Again',6000,'announcement-2').announcement.text,'Again');});
test('only fresh messages on connected sound owner play once',()=>{const spoken=[];const audio=new DisplayAudio({sound:{announce:t=>spoken.push(t)},request:async()=>{},client:'a',now:()=>100});audio.active=true;audio.leaseUntil=200;audio.announce({id:'old',text:'Old',at:1000},1000);audio.announce({id:'new',text:'Hello',at:1000},1000);audio.announce({id:'new',text:'Hello',at:1000},1001);audio.announce({id:'stale',text:'Late',at:0},10000);audio.active=false;audio.announce({id:'muted',text:'Muted',at:1000},1000);audio.active=true;audio.announce({id:'muted',text:'Muted',at:1000},1001);assert.deepEqual(spoken,['Hello']);});
test('expired lease cannot announce; initial empty packet allows next message',()=>{const spoken=[];const audio=new DisplayAudio({sound:{announce:t=>spoken.push(t)},request:async()=>{},client:'a',now:()=>100});audio.active=true;audio.leaseUntil=99;audio.announce(null,1000);audio.announce({id:'a',text:'No lease',at:1000},1000);audio.leaseUntil=200;audio.announce({id:'b',text:'Owned',at:1001},1001);assert.deepEqual(spoken,['Owned']);});
import {CueAudio} from '../public/audio.js';
test('custom speech uses a local voice and chosen volume',async()=>{const spoken=[];globalThis.window={speechSynthesis:{getVoices:()=>[{localService:false,lang:'en-US'},{localService:true,lang:'en-US',name:'Local'}],speak:u=>spoken.push(u),cancel:()=>{}},SpeechSynthesisUtterance:class{constructor(text){this.text=text;}}};const audio=new CueAudio();audio.context={state:'running'};audio.enabled=true;audio.volume=.4;await audio.announce('Please take your seats.');await new Promise(r=>setTimeout(r,170));assert.equal(spoken.length,1);assert.equal(spoken[0].voice.name,'Local');assert.equal(spoken[0].volume,.4);audio.stop();delete globalThis.window;});

import {announceFromDirector} from '../public/director-announcement.js';
test('Announce unlocks director first, sends display command, then plays locally',async()=>{const calls=[];const sound={enable:async()=>calls.push('unlock'),announce:t=>{calls.push(t);return true;}};const result=await announceFromDirector({sound,text:'Seats please',volume:.6,send:async(type,args)=>{calls.push(type);assert.equal(args.text,'Seats please');return true;}});assert.deepEqual(calls,['unlock','announce','Seats please']);assert.equal(sound.volume,.6);assert.deepEqual(result,{sent:true,local:true});});
test('director audio failure does not prevent display delivery',async()=>{let sent=false;const sound={enable:async()=>{throw Error('blocked')},announce:()=>assert.fail()};const result=await announceFromDirector({sound,text:'Test',volume:.7,send:async()=>{sent=true;return true;}});assert.equal(sent,true);assert.deepEqual(result,{sent:true,local:false});});
test('rejected announcement does not play on director',async()=>{const sound={enable:async()=>{},announce:()=>assert.fail()};assert.deepEqual(await announceFromDirector({sound,text:'Test',volume:.7,send:async()=>false}),{sent:false,local:false});});
import {waitForLocalVoice} from '../public/speech-voices.js';
test('Edge delayed voice list is awaited and listener is removed',async()=>{let voices=[],listener;const synth={getVoices:()=>voices,addEventListener:(name,f)=>{listener=f},removeEventListener:(name,f)=>{assert.equal(f,listener);listener=null}};const pending=waitForLocalVoice(synth,{timeoutMs:100});voices=[{localService:true,lang:'en-US',name:'Delayed'}];listener();assert.equal((await pending).name,'Delayed');assert.equal(listener,null);});
test('remote-only voice list returns an honest unavailable result',async()=>{const synth={getVoices:()=>[{localService:false,lang:'en-US'}]};assert.equal(await waitForLocalVoice(synth,{timeoutMs:5}),null);});
test('closing or muting during voice loading cancels pending speech',async()=>{let voices=[],listener;globalThis.window={speechSynthesis:{getVoices:()=>voices,addEventListener:(n,f)=>listener=f,removeEventListener:()=>{},speak:()=>assert.fail('must not replay')},SpeechSynthesisUtterance:class{}};const audio=new CueAudio();audio.context={state:'running'};audio.enabled=true;const result=audio.announce('Never play');audio.disable();voices=[{localService:true,lang:'en-US'}];listener();assert.equal(await result,false);delete globalThis.window;});
