import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {deleteAccountData} from '../cloud/accounts/delete-account.js';
import {createAccountsHandler} from '../cloud/accounts/handler.js';
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',image='a'.repeat(64)+'.png';
function fixture(overrides={}){const calls=[];let listed=0;return {calls,options:{owner,begin:async id=>calls.push(['begin',id]),listImages:async id=>{calls.push(['list',id]);return listed++?[]:[{name:image}]},removeImages:async paths=>calls.push(['images',paths]),removeRows:async id=>calls.push(['rows',id]),removeLogin:async id=>calls.push(['login',id]),finish:async id=>calls.push(['finish',id]),...overrides}};}
test('deletion blocks writes first, removes storage then records then auth, marks completion last',async()=>{const h=fixture();assert.deepEqual(await deleteAccountData(h.options),{deleted:true});assert.deepEqual(h.calls.map(c=>c[0]),['begin','list','images','list','rows','login','finish']);assert.deepEqual(h.calls[2][1],[owner+'/'+image]);});
test('failed image removal keeps login intact and does not mark completed',async()=>{const h=fixture({removeImages:async()=>{throw Error('storage unavailable')}});await assert.rejects(deleteAccountData(h.options));assert.ok(!h.calls.some(c=>['rows','login','finish'].includes(c[0])));});
test('retry with images already gone still completes remaining steps',async()=>{const h=fixture({listImages:async()=>[]});await deleteAccountData(h.options);assert.deepEqual(h.calls.map(c=>c[0]),['begin','rows','login','finish']);});
test('unexpected storage paths cannot escape owner directory',async()=>{for(const name of ['../'+image,other+'/'+image,'folder','x.png']){const h=fixture({listImages:async()=>[{name}]});await assert.rejects(deleteAccountData(h.options));assert.ok(!h.calls.some(c=>['images','rows','login','finish'].includes(c[0])));}});
test('failed auth removal never claims successful deletion',async()=>{const h=fixture({listImages:async()=>[],removeLogin:async()=>{throw Error('retry')}});await assert.rejects(deleteAccountData(h.options));assert.ok(!h.calls.some(c=>c[0]==='finish'));});
test('account service ignores supplied victim owner and requires current password and confirmation',async()=>{
 const calls=[];const fetcher=async(url,options)=>{const path=new URL(url).pathname,body=options.body?JSON.parse(options.body):null;calls.push({path,body});let data={};if(path.endsWith('clock_auth_attempt'))data=true;else if(path==='/auth/v1/user')data={id:owner,email:'qa@accounts.pokerclock.invalid',email_confirmed_at:'2026-01-01',is_anonymous:false};else if(path.includes('clock_account_deletions'))data=[];else if(path==='/auth/v1/token')return new Response('{}',{status:400});else throw Error('Unexpected '+path);return new Response(JSON.stringify(data));};
 const handler=createAccountsHandler({url:'https://test.invalid',secretKey:'fixture',publishableKey:'public',fetcher});
 for(const body of [{owner,confirmation:'not confirmed',password:'x'},{owner:other,confirmation:'DELETE',password:'wrong'}]){const response=await handler(new Request('https://test.invalid/functions/v1/clock-accounts/delete',{method:'POST',headers:{Authorization:'Bearer fixture'},body:JSON.stringify(body)}));assert.equal(response.status,400);}
 assert.ok(!calls.some(c=>c.path.includes('begin_account_deletion')));
});
test('database guards cover in-flight artwork and tournament mutations with the same transaction lock',()=>{const sql=fs.readFileSync('cloud/accounts/deletion-schema.sql','utf8');assert.equal((sql.match(/pg_advisory_xact_lock/g)||[]).length,2);for(const name of ['clock_tournaments','clock_artwork_assets','clock_account_recovery','storage.objects'])assert.ok(sql.includes(name));assert.ok(!sql.includes('security definer'));assert.ok(sql.includes('revoke all on function public.clock_begin_account_deletion(uuid) from public,anon,authenticated'));});
test('bookkeeping failure after actual data removal does not strand the deleted user',async()=>{const h=fixture({listImages:async()=>[],finish:async()=>{throw Error('temporary')}});assert.deepEqual(await deleteAccountData(h.options),{deleted:true});assert.ok(h.calls.some(c=>c[0]==='login'));});
