import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync('cloud/clock/index.js','utf8').split('function platformKey(name)')[0];
const box={structuredClone,console,TextEncoder,TextDecoder,URL,URLSearchParams,Response,Request,Headers,crypto:globalThis.crypto};vm.createContext(box);vm.runInContext(source,box);
function setup(){let row={id:'id',owner_id:'owner',revision:4,record:{history:['kept only until delete']}};let deletes=0;const store={get:async()=>row,remove:async(id,owner,revision)=>{assert.equal(owner,'owner');assert.equal(revision,4);deletes++;row=null;return true;}};return {clock:new box.CloudClock(store),store,get row(){return row},get deletes(){return deletes}};}
test('permanent delete requires explicit confirmation and current revision',async()=>{const s=setup();await assert.rejects(s.clock.remove('id',{userId:'owner'},{revision:4}),/Confirm/);await assert.rejects(s.clock.remove('id',{userId:'owner'},{revision:3,confirmation:'DELETE'}),/changed/);assert.equal(s.deletes,0);});
test('other owners and display clients cannot delete',async()=>{const s=setup();for(const actor of [{userId:'other'},{publicDisplay:true}])await assert.rejects(s.clock.remove('id',actor,{revision:4,confirmation:'DELETE'}));assert.equal(s.deletes,0);});
test('delete removes full record and retry is safe',async()=>{const s=setup();const input={revision:4,confirmation:'DELETE'};assert.equal((await s.clock.remove('id',{userId:'owner'},input)).permanent,true);assert.equal(s.row,null);await s.clock.remove('id',{userId:'owner'},input);assert.equal(s.deletes,1);});
test('concurrent update stops deletion rather than removing newer state',async()=>{const s=setup();s.store.remove=async()=>false;await assert.rejects(s.clock.remove('id',{userId:'owner'},{revision:4,confirmation:'DELETE'}),/changed/);assert.ok(s.row);});
test('saved card destinations stay together and reuse has a separate leading toolbar',()=>{const s=fs.readFileSync('public/account.js','utf8');assert.match(s,/\['Open Director','director'\],\['Open Display','display'\]/);assert.match(s,/if\(action==='reuse'\)topActions.append\(button\)/);assert.doesNotMatch(s,/Create next night|heading.append\(a\)/);assert.match(s,/confirmation:'DELETE'/);});
test('loading animation stops for access errors and respects reduced motion',()=>{assert.match(fs.readFileSync('public/app.js','utf8'),/setAttribute\('aria-busy','false'\)/);assert.match(fs.readFileSync('public/loading.css','utf8'),/prefers-reduced-motion:reduce/);});
