import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createAccountsHandler,username,usernameEmail,nameFromEmail,normalizeCode,digest} from '../cloud/accounts/handler.js';
import {AccountAuthFlow} from '../public/account-auth.js';
const uid='11111111-1111-4111-8111-111111111111',email=usernameEmail('friday_poker');
const user={id:uid,email,email_confirmed_at:'2026-10-06T00:00:00Z',is_anonymous:false};
const session={user,access_token:'fixture-token'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status});
function harness(overrides={}){const calls=[];const handler=createAccountsHandler({url:'https://fixture.invalid',secretKey:'server-only',publishableKey:'public',fetcher:async(url,options)=>{const path=new URL(url).pathname,body=options.body?JSON.parse(options.body):undefined;calls.push({path,body,options});if(overrides[path])return overrides[path](body,options);if(path.endsWith('clock_auth_attempt'))return json(true);if(path==='/auth/v1/user')return json(user);if(path==='/auth/v1/token')return json(session);if(path==='/auth/v1/logout')return json({});if(path.includes('clock_account_recovery')||path.includes('clock_account_deletions'))return json([]);throw new Error('Unexpected '+path);}});return {calls,handler,request:(path,body,authorized=true)=>handler(new Request('https://fixture.invalid/functions/v1/clock-accounts'+path,{method:body===undefined?'GET':'POST',headers:{...(authorized?{Authorization:'Bearer fixture'}:{}),'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})}))};}
test('usernames normalize deterministically without email or path injection',()=>{assert.equal(username(' Brian_85 '),'brian_85');assert.equal(nameFromEmail(usernameEmail('Brian_85')),'brian_85');for(const n of ['a','1brian','a@b.com','../x','x+y','école','A'.repeat(25)])assert.throws(()=>username(n));assert.equal(nameFromEmail('legacy@example.com'),null);});
test('recovery codes require a full 256-bit token',()=>{assert.equal(normalizeCode('AA'.repeat(32)),'aa'.repeat(32));assert.throws(()=>normalizeCode('123456'));});
test('private profile rejects unauthenticated access',async()=>{const h=harness();assert.equal((await h.request('/profile',undefined,false)).status,401);assert.ok(!h.calls.some(c=>c.path.includes('clock_account_recovery')));});
test('rotation rechecks password and stores only the hashed code under verified owner',async()=>{const h=harness();const r=await h.request('/recovery-code',{password:'fixture-password'});assert.equal(r.status,200);const {code}=await r.json();const row=h.calls.find(c=>c.path.includes('clock_account_recovery')).body;assert.equal(row.owner_id,uid);assert.equal(row.code_hash,await digest(normalizeCode(code)));assert.notEqual(row.code_hash,normalizeCode(code));assert.ok(h.calls.some(c=>c.path==='/auth/v1/logout'));assert.ok(!JSON.stringify(row).includes('fixture-password'));});
test('wrong current password cannot rotate recovery code',async()=>{const h=harness({'/auth/v1/token':()=>json({error:'invalid'},400)});assert.equal((await h.request('/recovery-code',{password:'wrong'})).status,400);assert.ok(!h.calls.some(c=>c.path.includes('clock_account_recovery')));});
test('invalid or used recovery code cannot create a session',async()=>{const h=harness({'/rest/v1/rpc/clock_consume_recovery':()=>json(null)});assert.equal((await h.request('/recover',{code:'a'.repeat(64)},false)).status,400);assert.ok(!h.calls.some(c=>c.path.includes('/admin/')));});
test('valid recovery consumes verifier before generating one-time recovery token, sends no mail',async()=>{const h=harness({'/rest/v1/rpc/clock_consume_recovery':()=>json(uid),['/auth/v1/admin/users/'+uid]:()=>json(user),'/auth/v1/admin/generate_link':()=>json({hashed_token:'one-time-fixture'})});const r=await h.request('/recover',{code:'a'.repeat(64)},false);assert.equal(r.status,200);assert.deepEqual(await r.json(),{token_hash:'one-time-fixture'});assert.ok(h.calls.findIndex(c=>c.path.includes('consume_recovery'))<h.calls.findIndex(c=>c.path.includes('generate_link')));assert.ok(!h.calls.some(c=>c.path==='/auth/v1/recover'||c.path==='/auth/v1/otp'));});
test('rate limits stop recovery before code lookup',async()=>{const h=harness({'/rest/v1/rpc/clock_auth_attempt':()=>json(false)});assert.equal((await h.request('/recover',{code:'a'.repeat(64)},false)).status,429);assert.equal(h.calls.length,1);});
test('username signup keeps recovery code until explicitly acknowledged',async()=>{const client={onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),getSession:async()=>({data:{session:null}}),signUp:async()=>({data:{session,recoveryCode:'fixture-recovery'}})};const flow=new AccountAuthFlow({client,configured:true,origin:'https://fixture.invalid'});await flow.start();flow.choose('signup');assert.equal(await flow.submit({email:'brian',password:'long-fixture-password'}),true);assert.equal(flow.state.mode,'authenticated');assert.equal(flow.state.backupCode,'fixture-recovery');flow.dispose();});
test('recovery code flow uses no email sending method and binds reset to returned user',async()=>{const client={onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),getSession:async()=>({data:{session:null}}),recoverWithCode:async()=>({data:{session}}),updateUser:async()=>({data:{user}})};const flow=new AccountAuthFlow({client,configured:true,origin:'https://fixture.invalid'});await flow.start();flow.choose('reset');await flow.submit({email:'a'.repeat(64)});assert.equal(flow.state.mode,'recover');assert.equal(flow.canRecover(),true);await flow.submit({password:'new-fixture-password'});assert.equal(flow.state.mode,'authenticated');assert.equal(flow.canRecover(),false);flow.dispose();});
test('recovery tables and SQL functions have no anonymous or authenticated grants',()=>{const sql=fs.readFileSync('cloud/accounts/schema.sql','utf8');assert.match(sql,/enable row level security/);assert.ok(!/security definer/i.test(sql));assert.ok(!/grant .* to (anon|authenticated)/i.test(sql));assert.match(sql,/code_hash=null/);});
test('switching accounts during signup never displays the first account recovery code',async()=>{
 let resolveSignup,current=null;const otherSession={user:{...user,id:'22222222-2222-4222-8222-222222222222'},access_token:'other-fixture'};
 const client={onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),getSession:async()=>({data:{session:current}}),signUp:()=>new Promise(resolve=>resolveSignup=resolve)};
 const flow=new AccountAuthFlow({client,configured:true,origin:'https://fixture.invalid'});await flow.start();flow.choose('signup');const pending=flow.submit({email:'brian',password:'long-fixture-password'});
 current=otherSession;flow.receive('SIGNED_IN',otherSession);resolveSignup({data:{session,recoveryCode:'private-first-user-code'}});await pending;
 assert.equal(flow.state.session.user.id,otherSession.user.id);assert.ok(!flow.state.backupCode);flow.dispose();
});
test('failed sign-in still observes an account change made in another tab',async()=>{
 let rejectSignin,current=null;const client={onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),getSession:async()=>({data:{session:current}}),signInWithPassword:()=>new Promise((_,reject)=>rejectSignin=reject)};
 const flow=new AccountAuthFlow({client,configured:true,origin:'https://fixture.invalid'});await flow.start();const pending=flow.submit({email:'brian',password:'bad'});current=session;flow.receive('SIGNED_IN',session);rejectSignin(new Error('Invalid password'));await pending;assert.equal(flow.state.mode,'authenticated');assert.equal(flow.state.session.user.id,user.id);flow.dispose();
});
