import test from 'node:test';import assert from 'node:assert/strict';
import {renderArtwork} from '../public/artwork.js';
const ref=id=>({owner:'local',id:id.repeat(64)});
function fixture(){const writes=[],values=new Map(),images=[];globalThis.Image=class{constructor(){images.push(this);this.naturalWidth=100;this.naturalHeight=50;}set src(v){this.source=v;}};globalThis.document={createElement:()=>({getContext:()=>({drawImage(){}}),toDataURL:()=> 'data:image/png;base64,padded'})};return {writes,images,stage:{dataset:{},style:{getPropertyValue:k=>values.get(k)||'',setProperty:(k,v)=>{values.set(k,v);writes.push([k,v]);}}}};}
const appearance=background=>({artwork:{background,preset:'watermark',advanced:false}});
test('clock refreshes never replace a ready padded watermark with its original',async()=>{const f=fixture();try{const a=appearance(ref('a'));renderArtwork(f.stage,a);f.images[0].onload();await Promise.resolve();await Promise.resolve();assert.equal(f.stage.style.getPropertyValue('--art-image'),'url("data:image/png;base64,padded")');const n=f.writes.length;for(let i=0;i<20;i++)renderArtwork(f.stage,a);await Promise.resolve();assert.equal(f.writes.length,n);assert.equal(f.images.length,1);}finally{delete globalThis.Image;delete globalThis.document;}});
test('late image completion cannot resurrect an image removed from the display',async()=>{const f=fixture();try{renderArtwork(f.stage,appearance(ref('b')));renderArtwork(f.stage,appearance(null));f.images[0].onload();await Promise.resolve();await Promise.resolve();assert.equal(f.stage.dataset.mode,'none');assert.equal(f.stage.style.getPropertyValue('--art-image'),'none');}finally{delete globalThis.Image;delete globalThis.document;}});

test('all ordinary background modes retain a loaded frame through repeated clock renders',()=>{for(const mode of ['cover','contain','stretch','large','small']){const f=fixture();try{const a={backgroundArt:mode,artwork:{background:ref('c'),advanced:true}};renderArtwork(f.stage,a);f.images[0].onload();const n=f.writes.length;for(let i=0;i<30;i++)renderArtwork(f.stage,a);assert.equal(f.images.length,1,mode);assert.equal(f.writes.length,n,mode);assert.match(f.stage.style.getPropertyValue('--art-image'),/artwork\/local/);}finally{delete globalThis.Image;delete globalThis.document;}}});
test('ordinary background ignores a stale image load after selection or removal',()=>{const f=fixture();try{const a=background=>({artwork:{background,preset:'cover',advanced:false}});renderArtwork(f.stage,a(ref('d')));renderArtwork(f.stage,a(ref('e')));f.images[0].onload();assert.equal(f.stage.style.getPropertyValue('--art-image'),'none');f.images[1].onload();assert.match(f.stage.style.getPropertyValue('--art-image'),/eeee/);renderArtwork(f.stage,a(null));f.images[1].onload();assert.equal(f.stage.style.getPropertyValue('--art-image'),'none');}finally{delete globalThis.Image;delete globalThis.document;}});
